---
- hosts: ubuntu-server # Alias for group1
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure user {{ username }} exists
      user: # Create user
        name: "{{ username }}"
        password: "{{ password }}"
        update_password: on_create # Update password only if user is created
...