---
# tasks file for webserver
# Main logic of the role
- name: Install Nginx
  package:
    name: nginx
    state: present

- name: Deploy custom index page
  copy:
    src: custom_index.html
    dest: /usr/share/nginx/html/index.html
  notify: Restart Nginx

- name: Deploy custom Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart Nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes